### ISSUE TITLE
No pushes being sent

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-plugin-pushbullet#15]
- No entry appears in the profile menu. 
- Not getting any pushes
- Pushes working for other things, just not NodeBB

**Comment by barisusakli** [comment]
Profile menu link is fixed in https://github.com/NodeBB/NodeBB/commit/7f6518e4a60797e2747ac0aaff520177e845ace4

Not sure about the pushes not working.

**Comment by julianlam** [comment]
v2.0.4 added a test button to the user settings page. It also now correctly interprets the "enabled" checkbox, so try toggling that option and sending a test push.

**Comment by julianlam** [comment]
67a3f5f

**Comment by pitaj** [comment]
It appears that the devices aren't pulled correctly. Only selecting all devices works for me.
