### ISSUE TITLE
[v0.7.0-dev] Cannot "Enable Pushbullet Notifications" in Profile

### ISSUE THREAD

**Issue by endofline** [NodeBB/nodebb-plugin-pushbullet#16]
The check box does not stay checked after saving. The device selection sticks though.

**Comment by julianlam** [comment]
Hey @endofline -- thanks for letting me know. I'll take a look at this.

**Comment by julianlam** [comment]
Hello again -- testing this against latest NodeBB with v2.0.3 of the pushbullet plugin worked fine. Can you let me know if this is still an issue for you?

**Comment by endofline** [comment]
The version I'm using presently is 2.0.4 with nodebb commit 75657605ad27972cbcf605db4acf8ba3bb75bfec 

"Enable Pushbullet Notifications" still doesn't remain checked. Tested with my account and a friend as well. Interestingly the Send Test Notification link doesn't work for me (the first user associated) but works for him, but only once - he tried again but never managed to send another one ;P

**Comment by julianlam** [comment]
Redis or MongoDB?

**Comment by endofline** [comment]
MongoDB
