### ISSUE TITLE
Redirect bug

### ISSUE THREAD

**Issue by thelinuxlich** [NodeBB/nodebb-plugin-pushbullet#19]
I've setted the redirect url exactly like it is suggested on the plugin section and it is working but when I try to test it on pushbutton create-client page, after approving it redirects to http://FORUM_URL/pushbullet/auth#access_token=ACCESS_TOKEN and I get a "Internal error" page from NodeBB(but nothing on the logs)

**Comment by hixe33** [comment]
Same here. 
And when I try an association between a user account and Pushbullet, I get the following error from Pushbullet : "The param 'redirect_uri' has an invalid value.".

**Comment by julianlam** [comment]
Hey guys, 

Last I checked the OAuth config page on the pushbullet website was down, but if it's back up I'll give it another test.

**Comment by julianlam** [comment]
I'm not thinking Pushbullet values their OAuth clients highly...

**Comment by julianlam** [comment]
I've just set it up again with no issues... what is your `redirect_uri`?

**Comment by lookapanda** [comment]
Same here by the way. redirect_uri is set up correctly as referred in the admin page (e.g. https://blabla.com/pushbullet/auth)

**Comment by julianlam** [comment]
Right, and what is `url` in your `config.json`? It should also be `https://blabla.com` or so.

**Comment by lookapanda** [comment]
It is.

**Comment by hixe33** [comment]
Mine too.

**Comment by pitaj** [comment]
Everyone here, try adding an extra `/` between `/pushbullet/auth` and the domain of your site. 
Like this: `http://community.nodebb.org//pushbullet/auth`

**Comment by julianlam** [comment]
Closed via #26

**Comment by julianlam** [comment]
v3.1.1
