### ISSUE TITLE
Pushes are broken on android and iOS

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/nodebb-plugin-pushbullet#22]
Sadly pushbullet updated all its apps and broke the plugin a weeks ago.
As far as i know its probably pushbullet problem because on the webapp at pushbullet.com i still see notifications on the "following" section.
I put this here to let you know in case you can contact pushbullet or something

**Comment by julianlam** [comment]
This is for new apps I think, no? Pushes still _seem_ to be working on our community forum, although I couldn't really get them working  on my dev environment...

**Comment by martyalicante** [comment]
Its not working on community forum. 
Try to send yourself a test notification to your mobile.

**Comment by martyalicante** [comment]
Acfually a friend told me he got notification on android with 12h delay. 
On iOS nothing at the moment since the big app update from last week

**Comment by julianlam** [comment]
Some things are getting through...

I get every single registration attempt, but you're right, I'm not getting
topic notifications...

Perhaps it's a spam filter? If text is too similar...? Will have to bring
this up with @guzba

**Comment by julianlam** [comment]
@martyalicante Tested 15 Jul 2015 by sending a test notification on my dev env -- seems to be working again.

**Comment by martyalicante** [comment]
you been testing on iOS or android?

**Comment by julianlam** [comment]
Android, and the pushbullet extension on Chrome updated just now, so perhaps that may be something you could try...

**Comment by martyalicante** [comment]
i don't have android for testing, just tried on iOS and not working, hope they update the app

Website OK
![captura de pantalla 2015-07-15 a las 17 21 17](https://cloud.githubusercontent.com/assets/10746278/8702124/1993cccc-2b16-11e5-9856-62f7473dd313.png)

iOS App :(
![img_5452](https://cloud.githubusercontent.com/assets/10746278/8702227/c8b91e82-2b16-11e5-9128-bf9792e3c8ac.PNG)

**Comment by martyalicante** [comment]
they updated iOs app and now it receives notification but the experience is so bad, ti doesn't pop up iphone alerts, you only get the red icon on the app and also it never disappears.
 Now it quotes full post text on each notification and navigating through it becomes super slow. 
They killed my favourite app for node :cry: we need pushnode :dancer:
