### ISSUE TITLE
Pushbullet doesn't work anymore

### ISSUE THREAD

**Issue by lenovouser** [NodeBB/nodebb-plugin-pushbullet#24]
This is from **[community.nodebb.org](https://community.nodebb.org):**

![error](https://cloud.githubusercontent.com/assets/7549136/8889508/6304b9e2-32dd-11e5-9cd2-112fad129e5d.gif)

It is failing with:

```javascript
/pushbullet/%7Brelative_path%7D/pushbullet/setup Not Found
```

**Comment by bdharrington7** [comment]
+1

**Comment by lenovouser** [comment]
Works again!
