### ISSUE TITLE
Missing header image

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-plugin-pushbullet#28]
https://community.nodebb.org/pushbullet/settings

Not your fault but header image is no longer available on their server.
`https://www.pushbullet.com/img/header-logo.png`
404 Page not found

P.S. in the past Andrew pleased to post all issues on the main tracker, sorry for inconvenience

**Comment by julianlam** [comment]
No worries, to each their own. I prefer my plugins issues outside of the main repo.

**Comment by julianlam** [comment]
v3.1.3, thanks!
