### ISSUE TITLE
Cannot set redirect_uri to https, must be http

### ISSUE THREAD

**Issue by malyzeli** [NodeBB/nodebb-plugin-pushbullet#31]
Plugin seems to be outdated, on NodeBB v1.2.1 just throws internal error when redirecting back to forum during the auth process.

EDIT: The problem was somewhere else, see below.

**Comment by julianlam** [comment]
Confirmed working with v1.3.0. Ensure base URL matches redirect uri as set in Pushbullet

**Comment by malyzeli** [comment]
Can't get it working. Not sure what's the problem, can you please review what I did?

1. installed `nodebb-plugin-pushbullet`
2. activated the plugin and restarted NodeBB
3. created an account on Pushbullet.com
4. created an client application on Pushbullet.com with following values
- name: My NodeBB
- website_url: `https://nodebb.mywebsite.com`
- image_url: _blank_
- redirect_uri: `https://nodebb.mywebsite.com/pushbullet/auth`
- allowed_origin: _blank_
5. got client_id and client_secret generated, copied it into Plugins > Pushbullet in NodeBB administration
6. restarted NodeBB

7. navigated to Profile > Settings > Pushbullet
(now I see "This account is not currently associated with a Pushbullet account.")
8. clicked on "Associate account with Pushbullet"
(now I see "Grant `https://nodebb.mywebsite.com` access to your Pushbullet profile and data.")
9. clicked on "Approve"
now I got an error message above the button: "The param 'redirect_uri' has an invalid value." 

When I try to do "oauth test url" from Pushbullet client settings, I'm redirected to "Grant access..." dialog again. When I click on "Approve" there, I'm redirected to
`https://nodebb.mywebsite.com/pushbullet/auth#access_token=abcdefgh123456`
and my NodeBB shows Internal Error.

What am I doing wrong?

I followed Configuration in plugin readme step by step.

Please update the readme to allow also non-experienced people like me set it up without troubles.

(Also in step 3. there is wrong URL - plugin's setup page is not at `/admin/pushbullet` but at `/admin/plugins/pushbullet`)

**Comment by julianlam** [comment]
Odd... is your site running https? Seems like a bug you may need to elevate to Pushbullet...

**Comment by malyzeli** [comment]
Yes, my site is running https and is forcefully redirecting http to https. 
Setting the redirect_uri on http works and I can confirm plugin functionality now.

You are right that it seems more like a problem on Pushbullet side, I guess there is some regexp validation of redirect_uri which accepts http only. I read through Pushbullet documentation and they always use http in redirect_uri, so maybe it's intentional, not sure about the reason though.

If this is the case, I think it would be helpful to update plugin's readme and also text on plugin administration section so it displays http instead of https.
